spring:
    profiles:
        include: oauth2
    data:
        mongodb:
            uri: mongodb://database:27017/kanban

server:
    port: 9999

client:
    redirectUri: http://localhost:9998/oauth2-process